### ISSUE TITLE
Verification Bar Bug

### ISSUE THREAD

**Issue by bennchong** [sgworkpass/mobile#28]
If the profile tab is loaded before the other tabs, and then a "STORE" QR code is scanned, the verification service wouldn't run in the background due to the profile tab being mounted early on . 

Steps to reproduce: 

1. Clear profile in DevDebug
2. Navigate to profile tab to see the screen "No profile detected"
3. Scan a STORE QR code/Use DevDebug to load a profile
4. Head back to profile tab to see verification bar perpetually verifying.

Issue:
Profile container is mounted first, thus useEffect in profile container is called before acquiring a workpass. 

Solutions: 

- Re-run the verification services everytime we navigate to the profile tab 
- Place verifying service elsewhere other in useEffect
- ?

**Comment by samuellye98** [comment]
https://github.com/sgworkpass/mobile/pull/29
